[package]
name = "truffle-config"
version.workspace = true
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
anyhow = "1.0"
asphalt = { path = "../asphalt" }
fs-err = { version = "3.1", features = ["tokio"] }
